version: "2"
services:
  mariadb:
    image: "docker.io/bitnami/mariadb:10.3-debian-10"
    volumes:
      - "/Users/debabratakarfa/Projects/Interview/dgwork/mariadb_data:/bitnami/mariadb"
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: "docker.io/bitnami/wordpress-nginx:5-debian-10"
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "/Users/debabratakarfa/Projects/Interview/dgwork/wordpress_data:/bitnami/wordpress"
      - "./wordpress-server-block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf:ro"
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
